/*
* generated by Xtext
*/
package com.soluvas.saentity.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SaentityOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
