/*
 * generated by Xtext
 */
package com.soluvas.saentity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SaentityUiModule extends com.soluvas.saentity.ui.AbstractSaentityUiModule {
	public SaentityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
