/*
* generated by Xtext
*/
package com.soluvas.saentity.ui.contentassist;

import com.soluvas.saentity.ui.contentassist.AbstractSaentityProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SaentityProposalProvider extends AbstractSaentityProposalProvider {

}
