/*
 * generated by Xtext
 */
package com.soluvas.saentity.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SaentityExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.soluvas.saentity.ui.internal.SaentityActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.soluvas.saentity.ui.internal.SaentityActivator.getInstance().getInjector("com.soluvas.saentity.Saentity");
	}
	
}
