/*
* generated by Xtext
*/
package com.soluvas.saentity.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.soluvas.saentity.services.SaentityGrammarAccess;

public class SaentityParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SaentityGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.soluvas.saentity.parser.antlr.internal.InternalSaentityParser createParser(XtextTokenStream stream) {
		return new com.soluvas.saentity.parser.antlr.internal.InternalSaentityParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SaentityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SaentityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
