/*
* generated by Xtext
*/
package com.soluvas.saentity.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SaentityAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/soluvas/saentity/parser/antlr/internal/InternalSaentity.tokens");
	}
}
