/*
 * generated by Xtext
 */
package com.soluvas.saentity;

import net.danieldietrich.protectedregions.core.RegionParserFactory;
import net.danieldietrich.protectedregions.support.ProtectedRegionSupport;
import net.danieldietrich.protectedregions.xtext.BidiJavaIoFileSystemAccess;

import org.eclipse.xtext.generator.JavaIoFileSystemAccess;

import com.google.inject.Provides;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SaentityRuntimeModule extends com.soluvas.saentity.AbstractSaentityRuntimeModule {

//	public Class<? extends JavaIoFileSystemAccess> bindJavaIoFileSystemAccess() {
//		return BidiJavaIoFileSystemAccess.class;
//	}
	
	@Provides
	public JavaIoFileSystemAccess createJavaIoFileSystemAccess() {
		ProtectedRegionSupport prs = new ProtectedRegionSupport();
		prs.addParser(RegionParserFactory.createJavaParser(), ".java");
		prs.addParser(RegionParserFactory.createXmlParser(), ".xml", ".xhtml");
    	JavaIoFileSystemAccess fsa = new BidiJavaIoFileSystemAccess(prs);
    	return fsa;
	}
	
//	@Override
//	public void configure(Binder binder) {
//		super.configure(binder);
//		binder.bind(JavaIoFileSystemAccess.class).to
//	}
}
