/*
* generated by Xtext
*/
package com.soluvas.saentity;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SaentityUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.soluvas.saentity.ui.internal.SaentityActivator.getInstance().getInjector("com.soluvas.saentity.Saentity");
	}
	
}
